name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  assets_audio_player: ^3.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - audio/
  - images/
  - images/dicee/
  - images/magicball/
  - images/destini/
